services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - "6000:3306"
    expose:
      - "6000"
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080